export type InputType
  = 'text'
    | 'search'
    | 'number'
    | 'number-format'
    | 'currency'
    | 'email'
    | 'password'
    | 'datetime'
    | 'date'
    | 'year-month'
    | 'time'
    | 'hour-minute'
    | 'tel'
    | 'url'
    | 'checkbox'
    | 'radio'
