<script setup lang="ts">
// This file is generated by a script, do not edit.

import { ref } from 'vue'
import { DxtTestPage, DxtTestScreenshot } from '@dxtmisha/test'
import { aiList } from '../library/ai-list.wiki'

defineOptions({
  name: 'AiWiki'
})

const element = ref<HTMLElement>()
</script>

<template>
  <DxtTestScreenshot v-if="element" :element="element"/>
  <div ref="element">
    <DxtTestPage
      title="List of available UI components"
      description="Below is a list of Vue 3 components available in the UI. These components are available immediately and do not need to be imported."
    >
      <component
        v-for="(item, key) in aiList"
        :key="key"
        :is="item"
      />
    </DxtTestPage>
  </div>
</template>
