import { type StorybookProps, WikiStorybook } from '@dxtmisha/wiki'
import { wiki, wikiDescriptions } from '@dxtmisha/wiki/media'

import { wikiD1 } from '../../../wiki/wiki'
import { defaults } from './props'

const propsNames: StorybookProps = [
  // :propsList [!] System label / Системная метка
  { name: 'align', type: 'string', option: ['center', 'right', 'left'] },
  { name: 'arrowAlign', type: 'string', option: ['center', 'right', 'left'] },
  { name: 'arrowCarousel', type: 'boolean' },
  { name: 'arrowStepper', type: 'boolean' },
  { name: 'basic', type: 'boolean' },
  { name: 'block', type: 'boolean' },
  { name: 'boxed', type: 'boolean' },
  { name: 'cancel', type: 'string', option: ['auto', 'always', 'none'] },
  { name: 'cancelShow', type: 'boolean' },
  { name: 'caption', type: 'string | number' },
  { name: 'classic', type: 'boolean' },
  { name: 'counter', type: 'string | number' },
  { name: 'counterId', type: 'string' },
  { name: 'counterShow', type: 'boolean' },
  { name: 'counterTemplate', type: 'string' },
  { name: 'counterTop', type: 'boolean' },
  { name: 'detail', type: 'Record<string, any>' },
  { name: 'disabled', type: 'boolean' },
  { name: 'disabledNext', type: 'boolean' },
  { name: 'disabledPrevious', type: 'boolean' },
  { name: 'fieldCounterAttrs', type: 'ConstrBind<FieldCounterProps>' },
  { name: 'fieldLabelAttrs', type: 'ConstrBind<FieldLabelProps>' },
  { name: 'fieldMessageAttrs', type: 'ConstrBind<FieldMessageProps>' },
  { name: 'filled', type: 'boolean' },
  { name: 'focus', type: 'boolean' },
  { name: 'forceShowMessage', type: 'boolean' },
  { name: 'helperId', type: 'string' },
  { name: 'helperMessage', type: 'string' },
  { name: 'icon', type: 'IconValue<IconProps>' },
  { name: 'iconArrowLeft', type: 'IconValue<IconProps>' },
  { name: 'iconArrowRight', type: 'IconValue<IconProps>' },
  { name: 'iconAttrs', type: 'ConstrBind<IconProps>' },
  { name: 'iconClose', type: 'IconValue<IconProps>' },
  { name: 'iconDir', type: 'boolean' },
  { name: 'iconHide', type: 'boolean' },
  { name: 'iconMinus', type: 'IconValue<IconProps>' },
  { name: 'iconPalette', type: 'boolean' },
  { name: 'iconPlus', type: 'IconValue<IconProps>' },
  { name: 'iconTrailing', type: 'IconValue<IconProps>' },
  { name: 'iconTrailingDirOnly', type: 'boolean' },
  { name: 'iconTrailingPalette', type: 'boolean' },
  { name: 'iconTrailingTurnOnly', type: 'boolean' },
  { name: 'iconTurn', type: 'boolean' },
  { name: 'id', type: 'string | number' },
  { name: 'isSkeleton', type: 'boolean' },
  { name: 'isValue', type: 'boolean' },
  { name: 'label', type: 'NumberOrString' },
  { name: 'labelId', type: 'string' },
  { name: 'loading', type: 'boolean | ConstrBind<ProgressProps>' },
  { name: 'maxlength', type: 'string | number' },
  { name: 'outlined', type: 'boolean' },
  { name: 'prefix', type: 'string | number' },
  { name: 'readonly', type: 'boolean' },
  { name: 'required', type: 'boolean' },
  { name: 'selected', type: 'boolean' },
  { name: 'size', type: 'string', option: ['sm', 'md', 'lg', 'display'] },
  { name: 'suffix', type: 'string | number' },
  { name: 'to', type: 'string | RouteLocationAsRelativeGeneric | RouteLocationAsPathGeneric' },
  { name: 'tonal', type: 'boolean' },
  { name: 'validationId', type: 'string' },
  { name: 'validationMessage', type: 'string' },
  { name: 'value', type: 'EventClickValue[\'value\']' },
  { name: 'width', type: 'string', option: ['custom'] }
  // :propsList [!] System label / Системная метка
]

export const FieldWikiStorybook = new WikiStorybook(
  'Field',
  propsNames,
  defaults,
  wikiD1,
  wiki,
  wikiDescriptions
)
