import type { StorybookComponentsDescriptionItem } from '../../types/storybookTypes'

/**
 * Descriptions for Table component properties
 *
 * Описания свойств компонента Table
 */
export const wikiDescriptionsTable: StorybookComponentsDescriptionItem = {
  name: 'Table',
  description: {
    en: 'Table component orchestrating grid-like column indexes and list row records',
    ru: 'Компонент таблицы, координирующий сеточные индексы колонок и список строк данных'
  },
  possibilities: {
    en: [
      'structured representation of datasets in tabular form',
      'supports headers rendering via header property',
      'row-level selections and key extraction configuration',
      'sticky headers configuration with headerTop flag',
      'custom slot support for advanced table body styling'
    ],
    ru: [
      'структурированное представление наборов данных в табличном виде',
      'поддержка рендеринга шапки через свойство header',
      'выбор на уровне строк и настройка извлечения ключей',
      'настройка липкой шапки с помощью флага headerTop',
      'поддержка кастомных слотов для расширенного оформления тела таблицы'
    ]
  },
  import: [],
  render: `
    <DesignComponent v-bind="args" />
  `,
  stories: [
    {
      id: 'TableDefault',
      name: {
        en: 'Default',
        ru: 'По умолчанию'
      },
      template: `
        <div class="wiki-storybook-item wiki-storybook-item--rectangle wiki-storybook-item--overflowAuto wiki-storybook-item--padding" style="max-height: 360px;">
          <DesignComponent
            :columns="['id', 'name', 'status', 'role', 'email', 'age', 'country', 'city', 'salary']"
            :headerTop="true"
            :header="[
              {
                id: { label: 'ID', rowspan: 2, description: 'Index', tooltipLabel: 'Identifier', tooltipDescription: 'Unique number of the record.' },
                name: { label: 'Main info', colspan: 2, align: 'center', tooltipLabel: 'General info', tooltipDescription: 'Full name and active status.' },
                status: { style: { display: 'none' } },
                role: { label: 'Work', colspan: 3, align: 'center', tooltipLabel: 'Employment details', tooltipDescription: 'Job title, contact email, and age.' },
                email: { style: { display: 'none' } },
                age: { style: { display: 'none' } },
                country: { label: 'Address', colspan: 3, align: 'center', tooltipLabel: 'Location & Compensation', tooltipDescription: 'Location details and current salary.' },
                city: { style: { display: 'none' } },
                salary: { style: { display: 'none' } }
              },
              {
                id: '*none',
                name: 'Name',
                status: 'Status',
                role: 'Role',
                email: 'Email',
                age: 'Age',
                country: 'Country',
                city: 'City',
                salary: 'Salary'
              }
            ]"
            :tableItemColumnAttrs="{ id: { align: 'right' }, age: { align: 'right' }, salary: { align: 'right' } }"
            :list="[
              { id: '1', name: 'Elizabeth Perez', status: 'Active', role: 'Frontend Developer', email: 'elizabeth.perez1@example.com', age: 35, country: 'Vietnam', city: 'Da Nang', salary: '$8,400' },
              { id: '2', name: 'Viet White', status: 'Active', role: 'Support Specialist', email: 'viet.white2@example.com', age: 41, country: 'Canada', city: 'Montreal', salary: '$9,300' },
              { id: '3', name: 'Dorothy Thompson', status: 'Active', role: 'Software Engineer', email: 'dorothy.thompson3@example.com', age: 47, country: 'Japan', city: 'Kyoto', salary: '$4,200' },
              { id: '4', name: 'Minh Walker', status: 'Inactive', role: 'System Administrator', email: 'minh.walker4@example.com', age: 53, country: 'Germany', city: 'Frankfurt', salary: '$5,100' },
              { id: '5', name: 'Pamela Clark', status: 'Pending', role: 'Backend Developer', email: 'pamela.clark5@example.com', age: 59, country: 'UK', city: 'Manchester', salary: '$6,000' },
              { id: '6', name: 'Giang King', status: 'Active', role: 'DevOps Engineer', email: 'giang.king6@example.com', age: 65, country: 'USA', city: 'Seattle', salary: '$6,900' },
              { id: '7', name: 'Thomas Scott', status: 'Active', role: 'UI/UX Designer', email: 'thomas.scott7@example.com', age: 26, country: 'Singapore', city: 'Singapore', salary: '$7,800' },
              { id: '8', name: 'Viet Smith', status: 'Active', role: 'Data Scientist', email: 'viet.smith8@example.com', age: 32, country: 'France', city: 'Marseille', salary: '$8,700' },
              { id: '9', name: 'Dung Nguyen', status: 'Active', role: 'HR Specialist', email: 'dung.nguyen9@example.com', age: 38, country: 'Australia', city: 'Sydney', salary: '$9,600' },
              { id: '10', name: 'Huong Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'huong.nguyen10@example.com', age: 44, country: 'Vietnam', city: 'Da Nang', salary: '$10,500' },
              { id: '11', name: 'Richard Moore', status: 'Active', role: 'Frontend Developer', email: 'richard.moore11@example.com', age: 50, country: 'Canada', city: 'Montreal', salary: '$11,400' },
              { id: '12', name: 'Sarah Perez', status: 'Active', role: 'Support Specialist', email: 'sarah.perez12@example.com', age: 56, country: 'Japan', city: 'Kyoto', salary: '$12,300' },
              { id: '13', name: 'Viet Martinez', status: 'Active', role: 'Software Engineer', email: 'viet.martinez13@example.com', age: 62, country: 'Germany', city: 'Frankfurt', salary: '$13,200' },
              { id: '14', name: 'Dung Wilson', status: 'Active', role: 'System Administrator', email: 'dung.wilson14@example.com', age: 23, country: 'UK', city: 'Manchester', salary: '$14,100' },
              { id: '15', name: 'Mark Harris', status: 'Active', role: 'Backend Developer', email: 'mark.harris15@example.com', age: 29, country: 'USA', city: 'Seattle', salary: '$15,000' },
              { id: '16', name: 'Viet Clark', status: 'Active', role: 'DevOps Engineer', email: 'viet.clark16@example.com', age: 35, country: 'Singapore', city: 'Singapore', salary: '$3,900' },
              { id: '17', name: 'Giang Smith', status: 'Active', role: 'UI/UX Designer', email: 'giang.smith17@example.com', age: 41, country: 'France', city: 'Marseille', salary: '$4,800' },
              { id: '18', name: 'Elizabeth Miller', status: 'Active', role: 'Data Scientist', email: 'elizabeth.miller18@example.com', age: 47, country: 'Australia', city: 'Sydney', salary: '$5,700' },
              { id: '19', name: 'Viet Jones', status: 'Active', role: 'HR Specialist', email: 'viet.jones19@example.com', age: 53, country: 'Vietnam', city: 'Da Nang', salary: '$6,600' },
              { id: '20', name: 'An Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'an.nguyen20@example.com', age: 59, country: 'Canada', city: 'Montreal', salary: '$7,500' },
              { id: '21', name: 'Pamela Thomas', status: 'Active', role: 'Frontend Developer', email: 'pamela.thomas21@example.com', age: 65, country: 'Japan', city: 'Kyoto', salary: '$8,400' },
              { id: '22', name: 'An Smith', status: 'Active', role: 'Support Specialist', email: 'an.smith22@example.com', age: 26, country: 'Germany', city: 'Frankfurt', salary: '$9,300' },
              { id: '23', name: 'Tuan Smith', status: 'Active', role: 'Software Engineer', email: 'tuan.smith23@example.com', age: 32, country: 'UK', city: 'Manchester', salary: '$10,200' },
              { id: '24', name: 'Pamela Moore', status: 'Active', role: 'System Administrator', email: 'pamela.moore24@example.com', age: 38, country: 'USA', city: 'Seattle', salary: '$11,100' },
              { id: '25', name: 'Minh Walker', status: 'Active', role: 'Backend Developer', email: 'minh.walker25@example.com', age: 44, country: 'Singapore', city: 'Singapore', salary: '$12,000' },
              { id: '26', name: 'Pamela Nguyen', status: 'Active', role: 'DevOps Engineer', email: 'pamela.nguyen26@example.com', age: 50, country: 'France', city: 'Marseille', salary: '$12,900' },
              { id: '27', name: 'Minh Nguyen', status: 'Active', role: 'UI/UX Designer', email: 'minh.nguyen27@example.com', age: 56, country: 'Australia', city: 'Sydney', salary: '$13,800' },
              { id: '28', name: 'Pamela Nguyen', status: 'Active', role: 'Data Scientist', email: 'pamela.nguyen28@example.com', age: 62, country: 'Vietnam', city: 'Da Nang', salary: '$14,700' },
              { id: '29', name: 'Viet Martin', status: 'Active', role: 'HR Specialist', email: 'viet.martin29@example.com', age: 23, country: 'Canada', city: 'Montreal', salary: '$3,600' },
              { id: '30', name: 'Tuan Smith', status: 'Active', role: 'Marketing Specialist', email: 'tuan.smith30@example.com', age: 29, country: 'Japan', city: 'Kyoto', salary: '$4,500' },
              { id: '31', name: 'Giang Smith', status: 'Active', role: 'Frontend Developer', email: 'giang.smith31@example.com', age: 35, country: 'Germany', city: 'Frankfurt', salary: '$5,400' },
              { id: '32', name: 'Linh White', status: 'Active', role: 'Support Specialist', email: 'linh.white32@example.com', age: 41, country: 'UK', city: 'Manchester', salary: '$6,300' },
              { id: '33', name: 'Linh Thompson', status: 'Active', role: 'Software Engineer', email: 'linh.thompson33@example.com', age: 47, country: 'USA', city: 'Seattle', salary: '$7,200' },
              { id: '34', name: 'Viet Walker', status: 'Active', role: 'System Administrator', email: 'viet.walker34@example.com', age: 53, country: 'Singapore', city: 'Singapore', salary: '$8,100' },
              { id: '35', name: 'Minh Clark', status: 'Active', role: 'Backend Developer', email: 'minh.clark35@example.com', age: 59, country: 'France', city: 'Marseille', salary: '$9,000' },
              { id: '36', name: 'Linh King', status: 'Active', role: 'DevOps Engineer', email: 'linh.king36@example.com', age: 65, country: 'Australia', city: 'Sydney', salary: '$9,900' },
              { id: '37', name: 'Quynh Scott', status: 'Active', role: 'UI/UX Designer', email: 'quynh.scott37@example.com', age: 26, country: 'Vietnam', city: 'Da Nang', salary: '$10,800' },
              { id: '38', name: 'Yen Smith', status: 'Active', role: 'Data Scientist', email: 'yen.smith38@example.com', age: 32, country: 'Canada', city: 'Montreal', salary: '$11,700' },
              { id: '39', name: 'Tuan Nguyen', status: 'Active', role: 'HR Specialist', email: 'tuan.nguyen39@example.com', age: 38, country: 'Japan', city: 'Kyoto', salary: '$12,600' },
              { id: '40', name: 'Viet Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'viet.nguyen40@example.com', age: 44, country: 'Germany', city: 'Frankfurt', salary: '$13,500' },
              { id: '41', name: 'Minh Moore', status: 'Active', role: 'Frontend Developer', email: 'minh.moore41@example.com', age: 50, country: 'UK', city: 'Manchester', salary: '$14,400' },
              { id: '42', name: 'Linh Perez', status: 'Active', role: 'Support Specialist', email: 'linh.perez42@example.com', age: 56, country: 'USA', city: 'Seattle', salary: '$3,300' },
              { id: '43', name: 'Yen Martinez', status: 'Active', role: 'Software Engineer', email: 'yen.martinez43@example.com', age: 62, country: 'Singapore', city: 'Singapore', salary: '$4,200' },
              { id: '44', name: 'Linh Wilson', status: 'Active', role: 'System Administrator', email: 'linh.wilson44@example.com', age: 23, country: 'France', city: 'Marseille', salary: '$5,100' },
              { id: '45', name: 'Quynh Harris', status: 'Active', role: 'Backend Developer', email: 'quynh.harris45@example.com', age: 29, country: 'Australia', city: 'Sydney', salary: '$6,000' },
              { id: '46', name: 'Linh Clark', status: 'Active', role: 'DevOps Engineer', email: 'linh.clark46@example.com', age: 35, country: 'Vietnam', city: 'Da Nang', salary: '$6,900' },
              { id: '47', name: 'Duc Smith', status: 'Active', role: 'UI/UX Designer', email: 'duc.smith47@example.com', age: 41, country: 'Canada', city: 'Montreal', salary: '$7,800' },
              { id: '48', name: 'Viet Miller', status: 'Active', role: 'Data Scientist', email: 'viet.miller48@example.com', age: 47, country: 'Japan', city: 'Kyoto', salary: '$8,700' },
              { id: '49', name: 'Linh Jones', status: 'Active', role: 'HR Specialist', email: 'linh.jones49@example.com', age: 53, country: 'Germany', city: 'Frankfurt', salary: '$9,600' },
              { id: '50', name: 'Viet Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'viet.nguyen50@example.com', age: 59, country: 'UK', city: 'Manchester', salary: '$10,500' },
              { id: '51', name: 'Duc Thomas', status: 'Active', role: 'Frontend Developer', email: 'duc.thomas51@example.com', age: 65, country: 'USA', city: 'Seattle', salary: '$11,400' },
              { id: '52', name: 'Minh Smith', status: 'Active', role: 'Support Specialist', email: 'minh.smith52@example.com', age: 26, country: 'Singapore', city: 'Singapore', salary: '$12,300' },
              { id: '53', name: 'Linh Smith', status: 'Active', role: 'Software Engineer', email: 'linh.smith53@example.com', age: 32, country: 'France', city: 'Marseille', salary: '$13,200' },
              { id: '54', name: 'Duc Moore', status: 'Active', role: 'System Administrator', email: 'duc.moore54@example.com', age: 38, country: 'Australia', city: 'Sydney', salary: '$14,100' },
              { id: '55', name: 'Yen Walker', status: 'Active', role: 'Backend Developer', email: 'yen.walker55@example.com', age: 44, country: 'Vietnam', city: 'Da Nang', salary: '$15,000' },
              { id: '56', name: 'Duc Nguyen', status: 'Active', role: 'DevOps Engineer', email: 'duc.nguyen56@example.com', age: 50, country: 'Canada', city: 'Montreal', salary: '$3,900' },
              { id: '57', name: 'Yen Nguyen', status: 'Active', role: 'UI/UX Designer', email: 'yen.nguyen57@example.com', age: 56, country: 'Japan', city: 'Kyoto', salary: '$4,800' },
              { id: '58', name: 'Duc Nguyen', status: 'Active', role: 'Data Scientist', email: 'duc.nguyen58@example.com', age: 62, country: 'Germany', city: 'Frankfurt', salary: '$5,700' },
              { id: '59', name: 'Linh Martin', status: 'Active', role: 'HR Specialist', email: 'linh.martin59@example.com', age: 23, country: 'UK', city: 'Manchester', salary: '$6,600' },
              { id: '60', name: 'Linh Smith', status: 'Active', role: 'Marketing Specialist', email: 'linh.smith60@example.com', age: 29, country: 'USA', city: 'Seattle', salary: '$7,500' },
              { id: '61', name: 'Duc Smith', status: 'Active', role: 'Frontend Developer', email: 'duc.smith61@example.com', age: 35, country: 'Singapore', city: 'Singapore', salary: '$8,400' },
              { id: '62', name: 'Trang White', status: 'Active', role: 'Support Specialist', email: 'trang.white62@example.com', age: 41, country: 'France', city: 'Marseille', salary: '$9,300' },
              { id: '63', name: 'Trang Thompson', status: 'Active', role: 'Software Engineer', email: 'trang.thompson63@example.com', age: 47, country: 'Australia', city: 'Sydney', salary: '$10,200' },
              { id: '64', name: 'Linh Walker', status: 'Active', role: 'System Administrator', email: 'linh.walker64@example.com', age: 53, country: 'Vietnam', city: 'Da Nang', salary: '$11,100' },
              { id: '65', name: 'Yen Clark', status: 'Active', role: 'Backend Developer', email: 'yen.clark65@example.com', age: 59, country: 'Canada', city: 'Montreal', salary: '$12,000' },
              { id: '66', name: 'Trang King', status: 'Active', role: 'DevOps Engineer', email: 'trang.king66@example.com', age: 65, country: 'Japan', city: 'Kyoto', salary: '$12,900' },
              { id: '67', name: 'Duc Scott', status: 'Active', role: 'UI/UX Designer', email: 'duc.scott67@example.com', age: 26, country: 'Germany', city: 'Frankfurt', salary: '$13,800' },
              { id: '68', name: 'Hai Smith', status: 'Active', role: 'Data Scientist', email: 'hai.smith68@example.com', age: 32, country: 'UK', city: 'Manchester', salary: '$14,700' },
              { id: '69', name: 'Linh Nguyen', status: 'Active', role: 'HR Specialist', email: 'linh.nguyen69@example.com', age: 38, country: 'USA', city: 'Seattle', salary: '$3,600' },
              { id: '70', name: 'Linh Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'linh.nguyen70@example.com', age: 44, country: 'Singapore', city: 'Singapore', salary: '$4,500' },
              { id: '71', name: 'Yen Moore', status: 'Active', role: 'Frontend Developer', email: 'yen.moore71@example.com', age: 50, country: 'France', city: 'Marseille', salary: '$5,400' },
              { id: '72', name: 'Trang Perez', status: 'Active', role: 'Support Specialist', email: 'trang.perez72@example.com', age: 56, country: 'Australia', city: 'Sydney', salary: '$6,300' },
              { id: '73', name: 'Hai Martinez', status: 'Active', role: 'Software Engineer', email: 'hai.martinez73@example.com', age: 62, country: 'Vietnam', city: 'Da Nang', salary: '$7,200' },
              { id: '74', name: 'Trang Wilson', status: 'Active', role: 'System Administrator', email: 'trang.wilson74@example.com', age: 23, country: 'Canada', city: 'Montreal', salary: '$8,100' },
              { id: '75', name: 'Duc Harris', status: 'Active', role: 'Backend Developer', email: 'duc.harris75@example.com', age: 29, country: 'Japan', city: 'Kyoto', salary: '$9,000' },
              { id: '76', name: 'Trang Clark', status: 'Active', role: 'DevOps Engineer', email: 'trang.clark76@example.com', age: 35, country: 'Germany', city: 'Frankfurt', salary: '$9,900' },
              { id: '77', name: 'Phong Smith', status: 'Active', role: 'UI/UX Designer', email: 'phong.smith77@example.com', age: 41, country: 'UK', city: 'Manchester', salary: '$10,800' },
              { id: '78', name: 'Linh Miller', status: 'Active', role: 'Data Scientist', email: 'linh.miller78@example.com', age: 47, country: 'USA', city: 'Seattle', salary: '$11,700' },
              { id: '79', name: 'Trang Jones', status: 'Active', role: 'HR Specialist', email: 'trang.jones79@example.com', age: 53, country: 'Singapore', city: 'Singapore', salary: '$12,600' },
              { id: '80', name: 'Linh Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'linh.nguyen80@example.com', age: 59, country: 'France', city: 'Marseille', salary: '$13,500' },
              { id: '81', name: 'Phong Thomas', status: 'Active', role: 'Frontend Developer', email: 'phong.thomas81@example.com', age: 65, country: 'Australia', city: 'Sydney', salary: '$14,400' },
              { id: '82', name: 'Yen Smith', status: 'Active', role: 'Support Specialist', email: 'yen.smith82@example.com', age: 26, country: 'Vietnam', city: 'Da Nang', salary: '$3,300' },
              { id: '83', name: 'Trang Smith', status: 'Active', role: 'Software Engineer', email: 'trang.smith83@example.com', age: 32, country: 'Canada', city: 'Montreal', salary: '$4,200' },
              { id: '84', name: 'Phong Moore', status: 'Active', role: 'System Administrator', email: 'phong.moore84@example.com', age: 38, country: 'Japan', city: 'Kyoto', salary: '$5,100' },
              { id: '85', name: 'Hai Walker', status: 'Active', role: 'Backend Developer', email: 'hai.walker85@example.com', age: 44, country: 'Germany', city: 'Frankfurt', salary: '$6,000' },
              { id: '86', name: 'Phong Nguyen', status: 'Active', role: 'DevOps Engineer', email: 'phong.nguyen86@example.com', age: 50, country: 'UK', city: 'Manchester', salary: '$6,900' },
              { id: '87', name: 'Hai Nguyen', status: 'Active', role: 'UI/UX Designer', email: 'hai.nguyen87@example.com', age: 56, country: 'USA', city: 'Seattle', salary: '$7,800' },
              { id: '88', name: 'Phong Nguyen', status: 'Active', role: 'Data Scientist', email: 'phong.nguyen88@example.com', age: 62, country: 'Singapore', city: 'Singapore', salary: '$8,700' },
              { id: '89', name: 'Trang Martin', status: 'Active', role: 'HR Specialist', email: 'trang.martin89@example.com', age: 23, country: 'France', city: 'Marseille', salary: '$9,600' },
              { id: '90', name: 'Trang Smith', status: 'Active', role: 'Marketing Specialist', email: 'trang.smith90@example.com', age: 29, country: 'Australia', city: 'Sydney', salary: '$10,500' },
              { id: '91', name: 'Phong Smith', status: 'Active', role: 'Frontend Developer', email: 'phong.smith91@example.com', age: 35, country: 'Vietnam', city: 'Da Nang', salary: '$11,400' },
              { id: '92', name: 'Khanh White', status: 'Active', role: 'Support Specialist', email: 'khanh.white92@example.com', age: 41, country: 'Canada', city: 'Montreal', salary: '$12,300' },
              { id: '93', name: 'Khanh Thompson', status: 'Active', role: 'Software Engineer', email: 'khanh.thompson93@example.com', age: 47, country: 'Japan', city: 'Kyoto', salary: '$13,200' },
              { id: '94', name: 'Trang Walker', status: 'Active', role: 'System Administrator', email: 'trang.walker94@example.com', age: 53, country: 'Germany', city: 'Frankfurt', salary: '$14,100' },
              { id: '95', name: 'Hai Clark', status: 'Active', role: 'Backend Developer', email: 'hai.clark95@example.com', age: 59, country: 'UK', city: 'Manchester', salary: '$15,000' },
              { id: '96', name: 'Khanh King', status: 'Active', role: 'DevOps Engineer', email: 'khanh.king96@example.com', age: 65, country: 'USA', city: 'Seattle', salary: '$3,900' },
              { id: '97', name: 'Phong Scott', status: 'Active', role: 'UI/UX Designer', email: 'phong.scott97@example.com', age: 26, country: 'Singapore', city: 'Singapore', salary: '$4,800' },
              { id: '98', name: 'Giang Smith', status: 'Active', role: 'Data Scientist', email: 'giang.smith98@example.com', age: 32, country: 'France', city: 'Marseille', salary: '$5,700' },
              { id: '99', name: 'Trang Nguyen', status: 'Active', role: 'HR Specialist', email: 'trang.nguyen99@example.com', age: 38, country: 'Australia', city: 'Sydney', salary: '$6,600' },
              { id: '100', name: 'Trang Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'trang.nguyen100@example.com', age: 44, country: 'Vietnam', city: 'Da Nang', salary: '$7,500' },
              { id: '101', name: 'Hai Moore', status: 'Active', role: 'Frontend Developer', email: 'hai.moore101@example.com', age: 50, country: 'Canada', city: 'Montreal', salary: '$8,400' },
              { id: '102', name: 'Khanh Perez', status: 'Active', role: 'Support Specialist', email: 'khanh.perez102@example.com', age: 56, country: 'Japan', city: 'Kyoto', salary: '$9,300' },
              { id: '103', name: 'Giang Martinez', status: 'Active', role: 'Software Engineer', email: 'giang.martinez103@example.com', age: 62, country: 'Germany', city: 'Frankfurt', salary: '$10,200' },
              { id: '104', name: 'Khanh Wilson', status: 'Active', role: 'System Administrator', email: 'khanh.wilson104@example.com', age: 23, country: 'UK', city: 'Manchester', salary: '$11,100' },
              { id: '105', name: 'Phong Harris', status: 'Active', role: 'Backend Developer', email: 'phong.harris105@example.com', age: 29, country: 'USA', city: 'Seattle', salary: '$12,000' },
              { id: '106', name: 'Khanh Clark', status: 'Active', role: 'DevOps Engineer', email: 'khanh.clark106@example.com', age: 35, country: 'Singapore', city: 'Singapore', salary: '$12,900' },
              { id: '107', name: 'Giang Smith', status: 'Active', role: 'UI/UX Designer', email: 'giang.smith107@example.com', age: 41, country: 'France', city: 'Marseille', salary: '$13,800' },
              { id: '108', name: 'Trang Miller', status: 'Active', role: 'Data Scientist', email: 'trang.miller108@example.com', age: 47, country: 'Australia', city: 'Sydney', salary: '$14,700' },
              { id: '109', name: 'Khanh Jones', status: 'Active', role: 'HR Specialist', email: 'khanh.jones109@example.com', age: 53, country: 'Vietnam', city: 'Da Nang', salary: '$3,600' },
              { id: '110', name: 'Trang Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'trang.nguyen110@example.com', age: 59, country: 'Canada', city: 'Montreal', salary: '$4,500' },
              { id: '111', name: 'Giang Thomas', status: 'Active', role: 'Frontend Developer', email: 'giang.thomas111@example.com', age: 65, country: 'Japan', city: 'Kyoto', salary: '$5,400' },
              { id: '112', name: 'Hai Smith', status: 'Active', role: 'Support Specialist', email: 'hai.smith112@example.com', age: 26, country: 'Germany', city: 'Frankfurt', salary: '$6,300' },
              { id: '113', name: 'Khanh Smith', status: 'Active', role: 'Software Engineer', email: 'khanh.smith113@example.com', age: 32, country: 'UK', city: 'Manchester', salary: '$7,200' },
              { id: '114', name: 'Giang Moore', status: 'Active', role: 'System Administrator', email: 'giang.moore114@example.com', age: 38, country: 'USA', city: 'Seattle', salary: '$8,100' },
              { id: '115', name: 'Giang Walker', status: 'Active', role: 'Backend Developer', email: 'giang.walker115@example.com', age: 44, country: 'Singapore', city: 'Singapore', salary: '$9,000' },
              { id: '116', name: 'Giang Nguyen', status: 'Active', role: 'DevOps Engineer', email: 'giang.nguyen116@example.com', age: 50, country: 'France', city: 'Marseille', salary: '$9,900' },
              { id: '117', name: 'Giang Nguyen', status: 'Active', role: 'UI/UX Designer', email: 'giang.nguyen117@example.com', age: 56, country: 'Australia', city: 'Sydney', salary: '$10,800' },
              { id: '118', name: 'Giang Nguyen', status: 'Active', role: 'Data Scientist', email: 'giang.nguyen118@example.com', age: 62, country: 'Vietnam', city: 'Da Nang', salary: '$11,700' },
              { id: '119', name: 'Khanh Martin', status: 'Active', role: 'HR Specialist', email: 'khanh.martin119@example.com', age: 23, country: 'Canada', city: 'Montreal', salary: '$12,600' },
              { id: '120', name: 'Khanh Smith', status: 'Active', role: 'Marketing Specialist', email: 'khanh.smith120@example.com', age: 29, country: 'Japan', city: 'Kyoto', salary: '$13,500' },
              { id: '121', name: 'Giang Smith', status: 'Active', role: 'Frontend Developer', email: 'giang.smith121@example.com', age: 35, country: 'Germany', city: 'Frankfurt', salary: '$14,400' },
              { id: '122', name: 'Thao White', status: 'Active', role: 'Support Specialist', email: 'thao.white122@example.com', age: 41, country: 'UK', city: 'Manchester', salary: '$3,300' },
              { id: '123', name: 'Thao Thompson', status: 'Active', role: 'Software Engineer', email: 'thao.thompson123@example.com', age: 47, country: 'USA', city: 'Seattle', salary: '$4,200' },
              { id: '124', name: 'Khanh Walker', status: 'Active', role: 'System Administrator', email: 'khanh.walker124@example.com', age: 53, country: 'Singapore', city: 'Singapore', salary: '$5,100' },
              { id: '125', name: 'Giang Clark', status: 'Active', role: 'Backend Developer', email: 'giang.clark125@example.com', age: 59, country: 'France', city: 'Marseille', salary: '$6,000' },
              { id: '126', name: 'Thao King', status: 'Active', role: 'DevOps Engineer', email: 'thao.king126@example.com', age: 65, country: 'Australia', city: 'Sydney', salary: '$6,900' },
              { id: '127', name: 'Giang Scott', status: 'Active', role: 'UI/UX Designer', email: 'giang.scott127@example.com', age: 26, country: 'Vietnam', city: 'Da Nang', salary: '$7,800' },
              { id: '128', name: 'Quynh Smith', status: 'Active', role: 'Data Scientist', email: 'quynh.smith128@example.com', age: 32, country: 'Canada', city: 'Montreal', salary: '$8,700' },
              { id: '129', name: 'Khanh Nguyen', status: 'Active', role: 'HR Specialist', email: 'khanh.nguyen129@example.com', age: 38, country: 'Japan', city: 'Kyoto', salary: '$9,600' },
              { id: '130', name: 'Khanh Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'khanh.nguyen130@example.com', age: 44, country: 'Germany', city: 'Frankfurt', salary: '$10,500' },
              { id: '131', name: 'Giang Moore', status: 'Active', role: 'Frontend Developer', email: 'giang.moore131@example.com', age: 50, country: 'UK', city: 'Manchester', salary: '$11,400' },
              { id: '132', name: 'Thao Perez', status: 'Active', role: 'Support Specialist', email: 'thao.perez132@example.com', age: 56, country: 'USA', city: 'Seattle', salary: '$12,300' },
              { id: '133', name: 'Quynh Martinez', status: 'Active', role: 'Software Engineer', email: 'quynh.martinez133@example.com', age: 62, country: 'Singapore', city: 'Singapore', salary: '$13,200' },
              { id: '134', name: 'Thao Wilson', status: 'Active', role: 'System Administrator', email: 'thao.wilson134@example.com', age: 23, country: 'France', city: 'Marseille', salary: '$14,100' },
              { id: '135', name: 'Giang Harris', status: 'Active', role: 'Backend Developer', email: 'giang.harris135@example.com', age: 29, country: 'Australia', city: 'Sydney', salary: '$15,000' },
              { id: '136', name: 'Thao Clark', status: 'Active', role: 'DevOps Engineer', email: 'thao.clark136@example.com', age: 35, country: 'Vietnam', city: 'Da Nang', salary: '$3,900' },
              { id: '137', name: 'Duc Smith', status: 'Active', role: 'UI/UX Designer', email: 'duc.smith137@example.com', age: 41, country: 'Canada', city: 'Montreal', salary: '$4,800' },
              { id: '138', name: 'Khanh Miller', status: 'Active', role: 'Data Scientist', email: 'khanh.miller138@example.com', age: 47, country: 'Japan', city: 'Kyoto', salary: '$5,700' },
              { id: '139', name: 'Thao Jones', status: 'Active', role: 'HR Specialist', email: 'thao.jones139@example.com', age: 53, country: 'Germany', city: 'Frankfurt', salary: '$6,600' },
              { id: '140', name: 'Khanh Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'khanh.nguyen140@example.com', age: 59, country: 'UK', city: 'Manchester', salary: '$7,500' },
              { id: '141', name: 'Duc Thomas', status: 'Active', role: 'Frontend Developer', email: 'duc.thomas141@example.com', age: 65, country: 'USA', city: 'Seattle', salary: '$8,400' },
              { id: '142', name: 'Giang Smith', status: 'Active', role: 'Support Specialist', email: 'giang.smith142@example.com', age: 26, country: 'Singapore', city: 'Singapore', salary: '$9,300' },
              { id: '143', name: 'Thao Smith', status: 'Active', role: 'Software Engineer', email: 'thao.smith143@example.com', age: 32, country: 'France', city: 'Marseille', salary: '$10,200' },
              { id: '144', name: 'Duc Moore', status: 'Active', role: 'System Administrator', email: 'duc.moore144@example.com', age: 38, country: 'Australia', city: 'Sydney', salary: '$11,100' },
              { id: '145', name: 'Duc Walker', status: 'Active', role: 'Backend Developer', email: 'duc.walker145@example.com', age: 44, country: 'Vietnam', city: 'Da Nang', salary: '$12,000' },
              { id: '146', name: 'Duc Nguyen', status: 'Active', role: 'DevOps Engineer', email: 'duc.nguyen146@example.com', age: 50, country: 'Canada', city: 'Montreal', salary: '$12,900' },
              { id: '147', name: 'Duc Nguyen', status: 'Active', role: 'UI/UX Designer', email: 'duc.nguyen147@example.com', age: 56, country: 'Japan', city: 'Kyoto', salary: '$13,800' },
              { id: '148', name: 'Duc Nguyen', status: 'Active', role: 'Data Scientist', email: 'duc.nguyen148@example.com', age: 62, country: 'Germany', city: 'Frankfurt', salary: '$14,700' },
              { id: '149', name: 'Thao Martin', status: 'Active', role: 'HR Specialist', email: 'thao.martin149@example.com', age: 23, country: 'UK', city: 'Manchester', salary: '$3,600' },
              { id: '150', name: 'Thao Smith', status: 'Active', role: 'Marketing Specialist', email: 'thao.smith150@example.com', age: 29, country: 'USA', city: 'Seattle', salary: '$4,500' },
              { id: '151', name: 'Duc Smith', status: 'Active', role: 'Frontend Developer', email: 'duc.smith151@example.com', age: 35, country: 'Singapore', city: 'Singapore', salary: '$5,400' },
              { id: '152', name: 'Quynh White', status: 'Active', role: 'Support Specialist', email: 'quynh.white152@example.com', age: 41, country: 'France', city: 'Marseille', salary: '$6,300' },
              { id: '153', name: 'Quynh Thompson', status: 'Active', role: 'Software Engineer', email: 'quynh.thompson153@example.com', age: 47, country: 'Australia', city: 'Sydney', salary: '$7,200' },
              { id: '154', name: 'Thao Walker', status: 'Active', role: 'System Administrator', email: 'thao.walker154@example.com', age: 53, country: 'Vietnam', city: 'Da Nang', salary: '$8,100' },
              { id: '155', name: 'Duc Clark', status: 'Active', role: 'Backend Developer', email: 'duc.clark155@example.com', age: 59, country: 'Canada', city: 'Montreal', salary: '$9,000' },
              { id: '156', name: 'Quynh King', status: 'Active', role: 'DevOps Engineer', email: 'quynh.king156@example.com', age: 65, country: 'Japan', city: 'Kyoto', salary: '$9,900' },
              { id: '157', name: 'Duc Scott', status: 'Active', role: 'UI/UX Designer', email: 'duc.scott157@example.com', age: 26, country: 'Germany', city: 'Frankfurt', salary: '$10,800' },
              { id: '158', name: 'Viet Smith', status: 'Active', role: 'Data Scientist', email: 'viet.smith158@example.com', age: 32, country: 'UK', city: 'Manchester', salary: '$11,700' },
              { id: '159', name: 'Thao Nguyen', status: 'Active', role: 'HR Specialist', email: 'thao.nguyen159@example.com', age: 38, country: 'USA', city: 'Seattle', salary: '$12,600' },
              { id: '160', name: 'Thao Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'thao.nguyen160@example.com', age: 44, country: 'Singapore', city: 'Singapore', salary: '$13,500' },
              { id: '161', name: 'Duc Moore', status: 'Active', role: 'Frontend Developer', email: 'duc.moore161@example.com', age: 50, country: 'France', city: 'Marseille', salary: '$14,400' },
              { id: '162', name: 'Quynh Perez', status: 'Active', role: 'Support Specialist', email: 'quynh.perez162@example.com', age: 56, country: 'Australia', city: 'Sydney', salary: '$3,300' },
              { id: '163', name: 'Viet Martinez', status: 'Active', role: 'Software Engineer', email: 'viet.martinez163@example.com', age: 62, country: 'Vietnam', city: 'Da Nang', salary: '$4,200' },
              { id: '164', name: 'Quynh Wilson', status: 'Active', role: 'System Administrator', email: 'quynh.wilson164@example.com', age: 23, country: 'Canada', city: 'Montreal', salary: '$5,100' },
              { id: '165', name: 'Duc Harris', status: 'Active', role: 'Backend Developer', email: 'duc.harris165@example.com', age: 29, country: 'Japan', city: 'Kyoto', salary: '$6,000' },
              { id: '166', name: 'Quynh Clark', status: 'Active', role: 'DevOps Engineer', email: 'quynh.clark166@example.com', age: 35, country: 'Germany', city: 'Frankfurt', salary: '$6,900' },
              { id: '167', name: 'An Smith', status: 'Active', role: 'UI/UX Designer', email: 'an.smith167@example.com', age: 41, country: 'UK', city: 'Manchester', salary: '$7,800' },
              { id: '168', name: 'Thao Miller', status: 'Active', role: 'Data Scientist', email: 'thao.miller168@example.com', age: 47, country: 'USA', city: 'Seattle', salary: '$8,700' },
              { id: '169', name: 'Quynh Jones', status: 'Active', role: 'HR Specialist', email: 'quynh.jones169@example.com', age: 53, country: 'Singapore', city: 'Singapore', salary: '$9,600' },
              { id: '170', name: 'Thao Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'thao.nguyen170@example.com', age: 59, country: 'France', city: 'Marseille', salary: '$10,500' },
              { id: '171', name: 'An Thomas', status: 'Active', role: 'Frontend Developer', email: 'an.thomas171@example.com', age: 65, country: 'Australia', city: 'Sydney', salary: '$11,400' },
              { id: '172', name: 'Thao Smith', status: 'Active', role: 'Support Specialist', email: 'thao.smith172@example.com', age: 26, country: 'Vietnam', city: 'Da Nang', salary: '$12,300' },
              { id: '173', name: 'Quynh Smith', status: 'Active', role: 'Software Engineer', email: 'quynh.smith173@example.com', age: 32, country: 'Canada', city: 'Montreal', salary: '$13,200' },
              { id: '174', name: 'An Moore', status: 'Active', role: 'System Administrator', email: 'an.moore174@example.com', age: 38, country: 'Japan', city: 'Kyoto', salary: '$14,100' },
              { id: '175', name: 'An Walker', status: 'Active', role: 'Backend Developer', email: 'an.walker175@example.com', age: 44, country: 'Germany', city: 'Frankfurt', salary: '$15,000' },
              { id: '176', name: 'An Nguyen', status: 'Active', role: 'DevOps Engineer', email: 'an.nguyen176@example.com', age: 50, country: 'UK', city: 'Manchester', salary: '$3,900' },
              { id: '177', name: 'An Nguyen', status: 'Active', role: 'UI/UX Designer', email: 'an.nguyen177@example.com', age: 56, country: 'USA', city: 'Seattle', salary: '$4,800' },
              { id: '178', name: 'An Nguyen', status: 'Active', role: 'Data Scientist', email: 'an.nguyen178@example.com', age: 62, country: 'Singapore', city: 'Singapore', salary: '$5,700' },
              { id: '179', name: 'Quynh Martin', status: 'Active', role: 'HR Specialist', email: 'quynh.martin179@example.com', age: 23, country: 'France', city: 'Marseille', salary: '$6,600' },
              { id: '180', name: 'Quynh Smith', status: 'Active', role: 'Marketing Specialist', email: 'quynh.smith180@example.com', age: 29, country: 'Australia', city: 'Sydney', salary: '$7,500' },
              { id: '181', name: 'An Smith', status: 'Active', role: 'Frontend Developer', email: 'an.smith181@example.com', age: 35, country: 'Vietnam', city: 'Da Nang', salary: '$8,400' },
              { id: '182', name: 'Minh White', status: 'Active', role: 'Support Specialist', email: 'minh.white182@example.com', age: 41, country: 'Canada', city: 'Montreal', salary: '$9,300' },
              { id: '183', name: 'Minh Thompson', status: 'Active', role: 'Software Engineer', email: 'minh.thompson183@example.com', age: 47, country: 'Japan', city: 'Kyoto', salary: '$10,200' },
              { id: '184', name: 'Quynh Walker', status: 'Active', role: 'System Administrator', email: 'quynh.walker184@example.com', age: 53, country: 'Germany', city: 'Frankfurt', salary: '$11,100' },
              { id: '185', name: 'An Clark', status: 'Active', role: 'Backend Developer', email: 'an.clark185@example.com', age: 59, country: 'UK', city: 'Manchester', salary: '$12,000' },
              { id: '186', name: 'Minh King', status: 'Active', role: 'DevOps Engineer', email: 'minh.king186@example.com', age: 65, country: 'USA', city: 'Seattle', salary: '$12,900' },
              { id: '187', name: 'An Scott', status: 'Active', role: 'UI/UX Designer', email: 'an.scott187@example.com', age: 26, country: 'Singapore', city: 'Singapore', salary: '$13,800' },
              { id: '188', name: 'Linh Smith', status: 'Active', role: 'Data Scientist', email: 'linh.smith188@example.com', age: 32, country: 'France', city: 'Marseille', salary: '$14,700' },
              { id: '189', name: 'Quynh Nguyen', status: 'Active', role: 'HR Specialist', email: 'quynh.nguyen189@example.com', age: 38, country: 'Australia', city: 'Sydney', salary: '$3,600' },
              { id: '190', name: 'Quynh Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'quynh.nguyen190@example.com', age: 44, country: 'Vietnam', city: 'Da Nang', salary: '$4,500' },
              { id: '191', name: 'An Moore', status: 'Active', role: 'Frontend Developer', email: 'an.moore191@example.com', age: 50, country: 'Canada', city: 'Montreal', salary: '$5,400' },
              { id: '192', name: 'Minh Perez', status: 'Active', role: 'Support Specialist', email: 'minh.perez192@example.com', age: 56, country: 'Japan', city: 'Kyoto', salary: '$6,300' },
              { id: '193', name: 'Linh Martinez', status: 'Active', role: 'Software Engineer', email: 'linh.martinez193@example.com', age: 62, country: 'Germany', city: 'Frankfurt', salary: '$7,200' },
              { id: '194', name: 'Minh Wilson', status: 'Active', role: 'System Administrator', email: 'minh.wilson194@example.com', age: 23, country: 'UK', city: 'Manchester', salary: '$8,100' },
              { id: '195', name: 'An Harris', status: 'Active', role: 'Backend Developer', email: 'an.harris195@example.com', age: 29, country: 'USA', city: 'Seattle', salary: '$9,000' },
              { id: '196', name: 'Minh Clark', status: 'Active', role: 'DevOps Engineer', email: 'minh.clark196@example.com', age: 35, country: 'Singapore', city: 'Singapore', salary: '$9,900' },
              { id: '197', name: 'Linh Smith', status: 'Active', role: 'UI/UX Designer', email: 'linh.smith197@example.com', age: 41, country: 'France', city: 'Marseille', salary: '$10,800' },
              { id: '198', name: 'Quynh Miller', status: 'Active', role: 'Data Scientist', email: 'quynh.miller198@example.com', age: 47, country: 'Australia', city: 'Sydney', salary: '$11,700' },
              { id: '199', name: 'Minh Jones', status: 'Active', role: 'HR Specialist', email: 'minh.jones199@example.com', age: 53, country: 'Vietnam', city: 'Da Nang', salary: '$12,600' },
              { id: '200', name: 'Quynh Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'quynh.nguyen200@example.com', age: 59, country: 'Canada', city: 'Montreal', salary: '$13,500' },
              { id: '201', name: 'Linh Thomas', status: 'Active', role: 'Frontend Developer', email: 'linh.thomas201@example.com', age: 65, country: 'Japan', city: 'Kyoto', salary: '$14,400' },
              { id: '202', name: 'Quynh Smith', status: 'Active', role: 'Support Specialist', email: 'quynh.smith202@example.com', age: 26, country: 'Germany', city: 'Frankfurt', salary: '$3,300' },
              { id: '203', name: 'Minh Smith', status: 'Active', role: 'Software Engineer', email: 'minh.smith203@example.com', age: 32, country: 'UK', city: 'Manchester', salary: '$4,200' },
              { id: '204', name: 'Linh Moore', status: 'Active', role: 'System Administrator', email: 'linh.moore204@example.com', age: 38, country: 'USA', city: 'Seattle', salary: '$5,100' },
              { id: '205', name: 'Linh Walker', status: 'Active', role: 'Backend Developer', email: 'linh.walker205@example.com', age: 44, country: 'Singapore', city: 'Singapore', salary: '$6,000' },
              { id: '206', name: 'Linh Nguyen', status: 'Active', role: 'DevOps Engineer', email: 'linh.nguyen206@example.com', age: 50, country: 'France', city: 'Marseille', salary: '$6,900' },
              { id: '207', name: 'Linh Nguyen', status: 'Active', role: 'UI/UX Designer', email: 'linh.nguyen207@example.com', age: 56, country: 'Australia', city: 'Sydney', salary: '$7,800' },
              { id: '208', name: 'Linh Nguyen', status: 'Active', role: 'Data Scientist', email: 'linh.nguyen208@example.com', age: 62, country: 'Vietnam', city: 'Da Nang', salary: '$8,700' },
              { id: '209', name: 'Minh Martin', status: 'Active', role: 'HR Specialist', email: 'minh.martin209@example.com', age: 23, country: 'Canada', city: 'Montreal', salary: '$9,600' },
              { id: '210', name: 'Minh Smith', status: 'Active', role: 'Marketing Specialist', email: 'minh.smith210@example.com', age: 29, country: 'Japan', city: 'Kyoto', salary: '$10,500' },
              { id: '211', name: 'Linh Smith', status: 'Active', role: 'Frontend Developer', email: 'linh.smith211@example.com', age: 35, country: 'Germany', city: 'Frankfurt', salary: '$11,400' },
              { id: '212', name: 'Huong White', status: 'Active', role: 'Support Specialist', email: 'huong.white212@example.com', age: 41, country: 'UK', city: 'Manchester', salary: '$12,300' },
              { id: '213', name: 'Huong Thompson', status: 'Active', role: 'Software Engineer', email: 'huong.thompson213@example.com', age: 47, country: 'USA', city: 'Seattle', salary: '$13,200' },
              { id: '214', name: 'Minh Walker', status: 'Active', role: 'System Administrator', email: 'minh.walker214@example.com', age: 53, country: 'Singapore', city: 'Singapore', salary: '$14,100' },
              { id: '215', name: 'Linh Clark', status: 'Active', role: 'Backend Developer', email: 'linh.clark215@example.com', age: 59, country: 'France', city: 'Marseille', salary: '$15,000' },
              { id: '216', name: 'Huong King', status: 'Active', role: 'DevOps Engineer', email: 'huong.king216@example.com', age: 65, country: 'Australia', city: 'Sydney', salary: '$3,900' },
              { id: '217', name: 'Linh Scott', status: 'Active', role: 'UI/UX Designer', email: 'linh.scott217@example.com', age: 26, country: 'Vietnam', city: 'Da Nang', salary: '$4,800' },
              { id: '218', name: 'Dung Smith', status: 'Active', role: 'Data Scientist', email: 'dung.smith218@example.com', age: 32, country: 'Canada', city: 'Montreal', salary: '$5,700' },
              { id: '219', name: 'Minh Nguyen', status: 'Active', role: 'HR Specialist', email: 'minh.nguyen219@example.com', age: 38, country: 'Japan', city: 'Kyoto', salary: '$6,600' },
              { id: '220', name: 'Minh Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'minh.nguyen220@example.com', age: 44, country: 'Germany', city: 'Frankfurt', salary: '$7,500' },
              { id: '221', name: 'Linh Moore', status: 'Active', role: 'Frontend Developer', email: 'linh.moore221@example.com', age: 50, country: 'UK', city: 'Manchester', salary: '$8,400' },
              { id: '222', name: 'Huong Perez', status: 'Active', role: 'Support Specialist', email: 'huong.perez222@example.com', age: 56, country: 'USA', city: 'Seattle', salary: '$9,300' },
              { id: '223', name: 'Dung Martinez', status: 'Active', role: 'Software Engineer', email: 'dung.martinez223@example.com', age: 62, country: 'Singapore', city: 'Singapore', salary: '$10,200' },
              { id: '224', name: 'Huong Wilson', status: 'Active', role: 'System Administrator', email: 'huong.wilson224@example.com', age: 23, country: 'France', city: 'Marseille', salary: '$11,100' },
              { id: '225', name: 'Linh Harris', status: 'Active', role: 'Backend Developer', email: 'linh.harris225@example.com', age: 29, country: 'Australia', city: 'Sydney', salary: '$12,000' },
              { id: '226', name: 'Huong Clark', status: 'Active', role: 'DevOps Engineer', email: 'huong.clark226@example.com', age: 35, country: 'Vietnam', city: 'Da Nang', salary: '$12,900' },
              { id: '227', name: 'Tu Smith', status: 'Active', role: 'UI/UX Designer', email: 'tu.smith227@example.com', age: 41, country: 'Canada', city: 'Montreal', salary: '$13,800' },
              { id: '228', name: 'Minh Miller', status: 'Active', role: 'Data Scientist', email: 'minh.miller228@example.com', age: 47, country: 'Japan', city: 'Kyoto', salary: '$14,700' },
              { id: '229', name: 'Huong Jones', status: 'Active', role: 'HR Specialist', email: 'huong.jones229@example.com', age: 53, country: 'Germany', city: 'Frankfurt', salary: '$3,600' },
              { id: '230', name: 'Minh Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'minh.nguyen230@example.com', age: 59, country: 'UK', city: 'Manchester', salary: '$4,500' },
              { id: '231', name: 'Tu Thomas', status: 'Active', role: 'Frontend Developer', email: 'tu.thomas231@example.com', age: 65, country: 'USA', city: 'Seattle', salary: '$5,400' },
              { id: '232', name: 'Linh Smith', status: 'Active', role: 'Support Specialist', email: 'linh.smith232@example.com', age: 26, country: 'Singapore', city: 'Singapore', salary: '$6,300' },
              { id: '233', name: 'Huong Smith', status: 'Active', role: 'Software Engineer', email: 'huong.smith233@example.com', age: 32, country: 'France', city: 'Marseille', salary: '$7,200' },
              { id: '234', name: 'Tu Moore', status: 'Active', role: 'System Administrator', email: 'tu.moore234@example.com', age: 38, country: 'Australia', city: 'Sydney', salary: '$8,100' },
              { id: '235', name: 'Tu Walker', status: 'Active', role: 'Backend Developer', email: 'tu.walker235@example.com', age: 44, country: 'Vietnam', city: 'Da Nang', salary: '$9,000' },
              { id: '236', name: 'Tu Nguyen', status: 'Active', role: 'DevOps Engineer', email: 'tu.nguyen236@example.com', age: 50, country: 'Canada', city: 'Montreal', salary: '$9,900' },
              { id: '237', name: 'Tu Nguyen', status: 'Active', role: 'UI/UX Designer', email: 'tu.nguyen237@example.com', age: 56, country: 'Japan', city: 'Kyoto', salary: '$10,800' },
              { id: '238', name: 'Tu Nguyen', status: 'Active', role: 'Data Scientist', email: 'tu.nguyen238@example.com', age: 62, country: 'Germany', city: 'Frankfurt', salary: '$11,700' },
              { id: '239', name: 'Huong Martin', status: 'Active', role: 'HR Specialist', email: 'huong.martin239@example.com', age: 23, country: 'UK', city: 'Manchester', salary: '$12,600' },
              { id: '240', name: 'Huong Smith', status: 'Active', role: 'Marketing Specialist', email: 'huong.smith240@example.com', age: 29, country: 'USA', city: 'Seattle', salary: '$13,500' },
              { id: '241', name: 'Tu Smith', status: 'Active', role: 'Frontend Developer', email: 'tu.smith241@example.com', age: 35, country: 'Singapore', city: 'Singapore', salary: '$14,400' },
              { id: '242', name: 'Tuan White', status: 'Active', role: 'Support Specialist', email: 'tuan.white242@example.com', age: 41, country: 'France', city: 'Marseille', salary: '$3,300' },
              { id: '243', name: 'Tuan Thompson', status: 'Active', role: 'Software Engineer', email: 'tuan.thompson243@example.com', age: 47, country: 'Australia', city: 'Sydney', salary: '$4,200' },
              { id: '244', name: 'Huong Walker', status: 'Active', role: 'System Administrator', email: 'huong.walker244@example.com', age: 53, country: 'Vietnam', city: 'Da Nang', salary: '$5,100' },
              { id: '245', name: 'Tu Clark', status: 'Active', role: 'Backend Developer', email: 'tu.clark245@example.com', age: 59, country: 'Canada', city: 'Montreal', salary: '$6,000' },
              { id: '246', name: 'Tuan King', status: 'Active', role: 'DevOps Engineer', email: 'tuan.king246@example.com', age: 65, country: 'Japan', city: 'Kyoto', salary: '$6,900' },
              { id: '247', name: 'Tu Scott', status: 'Active', role: 'UI/UX Designer', email: 'tu.scott247@example.com', age: 26, country: 'Germany', city: 'Frankfurt', salary: '$7,800' },
              { id: '248', name: 'Nam Smith', status: 'Active', role: 'Data Scientist', email: 'nam.smith248@example.com', age: 32, country: 'UK', city: 'Manchester', salary: '$8,700' },
              { id: '249', name: 'Huong Nguyen', status: 'Active', role: 'HR Specialist', email: 'huong.nguyen249@example.com', age: 38, country: 'USA', city: 'Seattle', salary: '$9,600' },
              { id: '250', name: 'Huong Nguyen', status: 'Active', role: 'Marketing Specialist', email: 'huong.nguyen250@example.com', age: 44, country: 'Singapore', city: 'Singapore', salary: '$10,500' },
              { id: '251', name: 'Tu Moore', status: 'Active', role: 'Frontend Developer', email: 'tu.moore251@example.com', age: 50, country: 'France', city: 'Marseille', salary: '$11,400' },
              { id: '252', name: 'Tuan Perez', status: 'Active', role: 'Support Specialist', email: 'tuan.perez252@example.com', age: 56, country: 'Australia', city: 'Sydney', salary: '$12,300' },
              { id: '253', name: 'Nam Martinez', status: 'Active', role: 'Software Engineer', email: 'nam.martinez253@example.com', age: 62, country: 'Vietnam', city: 'Da Nang', salary: '$13,200' },
              { id: '254', name: 'Tuan Wilson', status: 'Active', role: 'System Administrator', email: 'tuan.wilson254@example.com', age: 23, country: 'Canada', city: 'Montreal', salary: '$14,100' },
              { id: '255', name: 'Tu Harris', status: 'Active', role: 'Backend Developer', email: 'tu.harris255@example.com', age: 29, country: 'Japan', city: 'Kyoto', salary: '$15,000' },
              { id: '256', name: 'Tuan Clark', status: 'Active', role: 'DevOps Engineer', email: 'tuan.clark256@example.com', age: 35, country: 'Germany', city: 'Frankfurt', salary: '$3,900' }
            ]"
          />
        </div>
      `
    }
  ],
  documentation: {
    body: `
<StorybookDescriptions componentName={'Table'} type={'table'}/>

<StorybookDescriptions componentName={'Table'} type={'instruction'}/>

<StorybookDescriptions componentName={'Table'} type={'header'}/>
<Canvas of={Component.TableDefault}/>
    `,
    slots: `
<StorybookDescriptions componentName={'Table'} type={'slots'}/>
    `
  },
  ai: {
    render: `
<div :class="classDemo.item">
  <Table v-bind="args" />
</div>
    `,
    description: `
Flexible, modular and grid-like table component. Manages a columns array to render table rows, supporting custom header, lists, selection states, custom key extraction fields, and sticky headers.
Accepts body slots for complete layout customization. Controlled via columns, header (headers data), list (dataset array), and key/attributes mapping configurations.
`,
    hide: true
  }
}
